name: CI

on: push

jobs:
  test: 
    name: test node 18
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Node
      uses: actions/setup-node@master
      with:
        node-version: '18.x'


    - name: Install dependencies
      run: npm i
    - name: Unit tests
      run: npm run test --if-present
      env:
        CI: true
    - name: building
      run: npm run build
      env:
        CI: true
    - name: Test esm
      run: node CI/nodeEsm.mjs
      env:
        CI: true
    - name: Test cjs
      run: node CI/nodeCjs.js
      env:
        CI: true
    - name: Test deno
      run: deno run --allow-sys CI/deno.mjs
      env:
        CI: true
    - name: Test cli
      run: |
        npm link
        cross-platform-specs --help
        cross-platform-specs --version
        cross-platform-specs environment
        cross-platform-specs osName
        cross-platform-specs osVersion
        cross-platform-specs runtime
        cross-platform-specs runtimeVersion
        cross-platform-specs engine
        cross-platform-specs engineVersion
        cross-platform-specs cpuName
        cross-platform-specs cpuCores
        cross-platform-specs cpuArch
        cross-platform-specs memAvailable
        cross-platform-specs memFree
        cross-platform-specs

      env:
        CI: true
    - name: Test browser
      run: node CI/browser/main.mjs
      env:
        CI: true
     
        
        
        
        
        
        
        
        
        
        
        
        