name: CI

on: push

jobs:
  test: 
    name: test
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Node
      uses: actions/setup-node@master
      with:
        node-version: '16.x'


    - name: Install dependencies
      run: npm i
    - name: Testing
      run: npm run test --if-present

      env:
        CI: true

  nodeEsm: 
    name: node esm
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Node
      uses: actions/setup-node@master
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm i
    - name: Building
      run: npm run buildESM
    - name: Run checks
      run: node CI/nodeEsm.mjs

      env:
        CI: true


  nodeCjs:
    name: node cjs
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Node
      uses: actions/setup-node@master
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm i
    - name: Building
      run: npm run buildCJS
    - name: Run checks
      run: node CI/nodeCjs.js

      env:
        CI: true

  
  deno:
    name: deno
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Node
      uses: actions/setup-node@master
      with:
        node-version: '16.x'
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Install dependencies
      run: npm i
    - name: Building
      run: npm run buildESM
    - name: Run checks
      run: deno run CI/deno.mjs

      env:
        CI: true

  cli:
    name: cli
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Node
      uses: actions/setup-node@master
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm i
    - name: Building
      run: npm run buildESM
    - name: Linking CLI
      run: npm link
    - name: Run tests
      run: |
        cross-platform-specs --help
        cross-platform-specs environment
        cross-platform-specs osName
        cross-platform-specs osVersion
        cross-platform-specs runtime
        cross-platform-specs runtimeVersion
        cross-platform-specs engine
        cross-platform-specs engineVersion
        cross-platform-specs cpuName
        cross-platform-specs cpuCores
        cross-platform-specs cpuArch
        cross-platform-specs memAvailable
        cross-platform-specs memFree
        cross-platform-specs

      env:
        CI: true

        
        
        
        
        
        
        
        
        
        
        
        